### ISSUE TITLE
JOINs: tables and fields not between backticks (`)

### ISSUE THREAD

**Issue by pedzed** [tres-framework/Trestle#3] opened 2015-01-03 18:52 UTC
Title says it all. When you are making use of JOIN's, you won't get backticks, whereas JOINless queries will have them.

What I would do is get the string `example_table.example_field`, explode it, and join them together again but with backticks. A simple example:
```php
$str = 'example_table.example_field';
echo $str.'<br />';

list($table, $field) = explode('.', $str);

$str = '`'.$table.'`.`'.$field.'`';
echo $str.'<br />';
```
The problem with this is that the following (silly, but valid) example will fail: `` `example.table`.exampleField``. You could also look for backticks, but is it worth the effort?

@FireDart If you consider this unexpected behavior a bug, please add the bug label.

**Comment by FireDart** [comment] 2015-01-03 19:12
This was intended, what if a user makes a column name with a dot in it? ex...
```
table: articles
+----+------------+
| ID | post.title |
+----+------------+
| 1  | example 1  |
| 2  | example 2  |
| 3  | example 3  |
+----+------------+
```
While it looks silly to do that, in MySQL it is valid and it would become 
```
`articles`.`post`.`title`
```

Do you have any idea on a good solution?

**Comment by pedzed** [comment] 2015-01-03 20:16
A (temporary) fix could be that you just look if any backtick is found. If not, you could add them and otherwise, leave them as is.

**Comment by FireDart** [comment] 2015-01-03 20:34
Something that could be done is to use an array, first item is the table, second is the column
```php
$users = $db->get(['articles', 'users'], ['posts.id', 'posts.title', 'users.username'])
            ->where(['articles', 'posts.author'], '=', ['users', 'id'], true)
            ->exec();
```
As well if an array is spotted it is assumed it is a JOIN attempt so the `true` paramter could be dropped:
```php
$users = $db->get(['articles', 'users'], ['posts.id', 'posts.title', 'users.username'])
            ->where(['articles', 'posts.author'], '=', ['users', 'id'])
            ->exec();
```
It's more code to write but overall cleaner.

That just came to mind, I'll try it out in the dev branch.

**Comment by pedzed** [comment] 2015-01-03 21:08
> It's more code to write but overall cleaner.

I don't agree with that. I find it less clean actually.

This isn't a major problem at the moment: it can be postponed, but problems arise when more people use Trestle and when we have to look for backward compatibility. 

This is a bit off-topic, but isn't there a possibility to do the following?
```php
$tables = [
    'users' => [
        'id',
        'username',
        'email',
    ],
    'languages' => [
        'country_code' => 'language_country_code'
        // or: 'country_code AS language_country_code'
    ]
];

$users = $db->get($tables)
            ->where(['users', 'language_id'], '=', ['languages', 'id'])
            ->exec();
```

**Comment by pedzed** [comment] 2015-01-25 20:26
Should we just let the programmer add backticks?

**Comment by FireDart** [comment] 2015-02-25 01:38
And I still failed to close the issue with the commit message, 10/10 I'm really good at Git.

**Closed by FireDart** 2015-02-25 01:38 UTC
